# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: MIT License

from automated_retraining.query_strategies.base import BaseQuery
from automated_retraining.query_strategies.entropy_sampling import EntropySampling
from automated_retraining.query_strategies.margin_sampling import MarginSampling
from automated_retraining.query_strategies.uncertainty_sampling import UncertaintySampling
from automated_retraining.query_strategies.uniform_sampling import UniformSampling
